services:
  postgres:
    image: postgres
    container_name: example-database
    environment:
      POSTGRES_DB: example-database
      POSTGRES_USER: example-database
      POSTGRES_PASSWORD: example-database-password
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    networks:
      - pg-network


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-ppp
    ports:
      - 9411:9411


networks:
  pg-network:

volumes:
  pg-data: