server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - AuthenticationFilter
        - id: category-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/category/**
          filters:
            - AuthenticationFilter
        - id: brand-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/brand/**
          filters:
            - AuthenticationFilter
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
